### ISSUE TITLE
If number processing is turned on, it will cause the amount to be read incorrectly

### ISSUE THREAD

**Issue by cary-rowen** [ABuffEr/numberProcessing#3]
Hi @ABuffEr 

For example:
$100.00

would be reported as: 
1$00,00

Can you fix this flaw in an add-on?

**Comment by ABuffEr** [comment]
Hi @cary-rowen,
you're right, and sadly it does the same with € and probably other currencies... unfortunately, I suspect, it's a synthesizer behavior that happens after NumberProcessing work.
I can try to move the currency symbol after the amount preceeding the decimal sign, so you should get: 1 0 0 $ .00.

**Comment by cary-rowen** [comment]
Hi, @ABuffEr 

I made a little change, but I'm not sure if my method is reliable:
First change: `exp = re.compile(r'[\$\￥\💴\💵\💶\¥0-9\.]{%s,}'%userMinLen)`
Second change(in 'replaceFunc'): `	if fixedText[0] in ('$', '￥', '💴', '💵', '💶', '¥'): fixedText = fixedText[1:] + fixedText[0]`

The reason why the decimal point is replenished is because we are used to putting the currency symbol at the end in the Chinese environment.
With the regex I changed above, it might have one more flaw: the `userMinLen` variable might not be what the user expects when dealing with currency symbols and decimal points.

Thanks

**Comment by ABuffEr** [comment]
> The reason why the decimal point is replenished is because we are used to putting the currency symbol at the end in the Chinese environment.
Hi @cary-rowen,
can you elaborate this phrase a bit more? I'm not sure to have understood, not knowing the usual Chinese way to write currency amount.
Anyway, can you test changes I just made on master branch? I imagine you use git at this point, so I haven't done a new release 🙂
And sorry for closing, it has done automatically by Github when I pushed changes referencing this issue.

**Comment by cary-rowen** [comment]
@ABuffEr 
Thanks for your response.
In the Chinese reading order, people tend to put the currency symbol at the end of all numbers, even if there is a decimal point, such as:
* 1 0 . 4 5 ¥
* 1 0 0 . 5 3 ¥


Currently the add-on will process the above example into the following result:
* 1 0 0 ¥ . 5 3
* 1 0 ¥ . 4 5

Also, I think line 57 should include the decimal point, such as:
`basePattern = r'[\d\.]{%s,}'%userMinLen`

This enables the following example to be read numerically，, without missing decimal points:
2022.4.1

**Comment by ABuffEr** [comment]
Hi @cary-rowen,
thanks for explanation and examples.
I'm reluctant to change the main regexp, both because userMinLen would be adjusted, as you noted, and other undesired behaviors could be introduced.
Consider also that, basically, this add-on was born for phone numbers.
Anyway, I just pulled new changes, I Hope it's better now.

**Comment by cary-rowen** [comment]
Thanks for your efforts,
I tested this, and it works as I expect for currency symbols.
Even though this add-on was developed for phone numbers, I guess it can work elsewhere.

For example, for IP addresses separated by decimal points:

65.134.5.6

When the above address is minLen=2, only the first decimal point is read out.

65dot134   5    6

Do you think this situation can be handled by this add-on?

The speech synthesizer I use is Nuance Vocalizer expressive 2.2

**Comment by ABuffEr** [comment]
> When the above address is minLen=2, only the first decimal point is read out.
> 65dot134 5 6
> Do you think this situation can be handled by this add-on?
> The speech synthesizer I use is Nuance Vocalizer expressive 2.2

I haven't that synthesizer, but testing with Microsoft OneCore and dictionaries disabled I get each dot. Maybe it depends by symbol level and whether pass to synthesizer...
In a future version, sure, I'll try to provide a more customizable behavior, with ability to define user rules (phone numbers, IP addresses and so on), but it requires a complete and quite hard refactoring...

**Comment by cary-rowen** [comment]
As far as the problem stated in the title is concerned, this has been resolved.
So, I closed this.

**Comment by tareh7z** [comment]
Hi @ABuffEr and @cary-rowen!
I think two more symbols should be added to increase coverage. So far, I've noticed that the Korean won (₩) and the Vietnamese dong (₫) are missing.

**Comment by ABuffEr** [comment]
> So far, I've noticed that the Korean won (₩) and the Vietnamese dong (₫) are missing.

Yes, just added (they'll be in next release). Thanks!
