### ISSUE TITLE
Adding the option for enabling and disabling automatic number processing after NVDA startup

### ISSUE THREAD

**Issue by tareh7z** [ABuffEr/numberProcessing#6]
It would be good to add this feature because sometimes I forget to turn on number processing, which I always keep enabled. Primarily, I don't like having phone numbers read as +123456789 (+one hundred twenty-three million four hundred fifty-six thousand seven hundred eighty-nine). Maybe this could be a separate feature, but who knows.

**Comment by ABuffEr** [comment]
Hi @tarikhadzirovicofficial,
there is auto enable checkbox in settings. Is it not be sufficient?

**Comment by tareh7z** [comment]
Hi @ABuffEr!
For some reason, for me that checkbox is not displayed in the add-on settings.

**Comment by ABuffEr** [comment]
Hi,
what's version of NVDA are you using?
Is it the first time you install the add-on?
Can you start NVDA, open settings, close them and then copy/attach the log here?
Thanks.

**Comment by tareh7z** [comment]
Hi @ABuffEr!
I'm using NVDA 2024.2.
It was first time I installed the add-on.
After restarting the computer, the problem is somehow solved. I've tried that even before, but it didn't work.
