### ISSUE TITLE
Reading punctuation marks before numbers:

### ISSUE THREAD

**Issue by tareh7z** [ABuffEr/numberProcessing#8]
I understand that punctuation will be read if it is written together with the number. For example, 2.54 or Hello:12. The problem occurs when the punctuation mark is separated from the number. For example, Earned today: 12.50. NVDA reads: 'Earned today colon twelve point fifty.'

**Comment by ABuffEr** [comment]
Hi @tarikhadzirovicofficial,
thanks, it should be solved in [today build](https://github.com/ABuffEr/numberProcessing/releases/download/v1.0.20240813/numberProcessing-1.0.20240813.nvda-addon)
Test and close issue in the case 🙂
For @cary-rowen, I had to change a bit the money expression, just for reference.

**Comment by tareh7z** [comment]
Hi @ABuffEr!
Another issue related to punctuation, and partially to problem [#3](https://github.com/ABuffEr/numberProcessing/issues/3).  
I was reading online and came across the following text:  
"The official currency of Japan is the Japanese yen, and the symbol is ¥."  
The add-on here recognizes the period as a number and places it before the currency, even though it is supposed to be after the yen symbol.  
So, instead of the add-on simply saying "yen", it says "point yen".

**Comment by ABuffEr** [comment]
> So, instead of the add-on simply saying "yen", it says "point yen".

I see. It should be fixed in next release, even if the complexity of regexp that manages these cases is increasing, and this could introduce some slowdowns.
I'll release tomorrow.

**Comment by ABuffEr** [comment]
Hi,
please test the new [today build.](https://github.com/ABuffEr/numberProcessing/releases/download/v1.0.20240814/numberProcessing-1.0.20240814.nvda-addon)

Note that I changed the behavior of manual activation:

* when you enable processing from normal profile, then it's enabled everywhere; when you disable it, then it's disabled everywhere;
* if you enable from a different profile, then it's enabled (and disabled) just for that profile.

Auto enable feature should not be affected.

**Comment by tareh7z** [comment]
Hi @ABuffEr!
One problem gets fixed, and another one arises. 😂  
I don't remember how it was in the previous version. Now, if the sentence is:  
"I bought a bag for €5."  
The add-on says:  
"I bought a bag for five point euro."  
The same situation happens with other currency symbols (dollar, pound, yen, won, and dong).  
So, if a number is followed by a point, the add-on reads the number, point, and currency.  
However, if there's a comma at the end:  
"I bought a bag for €5, and a shirt for €7."  
The add-on doesn't read the euro sign for the number 5, but it does for the number 7.  
This issue occurs only with euros and dollars, while for pounds, yen, won, and dong, it does not.  
However, where the currency symbol is read (pound, yen, won, and dong), the add-on reads the number, pauses because of the comma, and then reads the currency.  
"I paid ¥410 for ice cream, and for a train ticket ¥14500."
So, the add-on reads four hundred ten [500 ms pause], five. At the end, it reads fourteen thousand five hundred point yen.  
As far as I remember from my work with regular expressions a long time ago, the add-on should not read the point if it is followed by anything other than a number, and it should not make a pause because of the comma. Although, it is quite complex for me now, so I'll leave it to you to figure out. 😊

**Comment by ABuffEr** [comment]
> As far as I remember from my work with regular expressions a long time ago, the add-on should not read the point if it is followed by anything other than a number, and it should not make a pause because of the comma.

Yes, something similar. The annoying fact is that I manage both €50,2, €50.2 and €50 with same regexp. Now (in next build for you) I have enforced the optional group "([,.]\d+)?", instead of "([,.]\d*)?" as before; it seems to pass all test cases.
Sorry for continous changes...

**Comment by tareh7z** [comment]
Hi @ABuffEr!
"Sorry for continous changes..."
That's okay, this is just a beta version of the add-on. I will test it again when a new build comes out and report the feedback, as always.

**Comment by ABuffEr** [comment]
Hi,
today build [is here.](https://github.com/ABuffEr/numberProcessing/releases/download/v1.0.20240815/numberProcessing-1.0.20240815.nvda-addon)

**Comment by tareh7z** [comment]
Hi @ABuffEr!
I'm sorry, due to a lack of time because of other commitments, I wasn't able to test the add-on today. I hope it's not a problem if you wait until tomorrow for me to test it, and I hope this delay won't affect your further development of the add-on.

**Comment by ABuffEr** [comment]
Hi,
don't worry, take your time! :)

**Comment by cary-rowen** [comment]
I tested some special cases and the add-on handled them well.
Just asking, does it add pauses in the middle of numbers? I noticed this behavior but I haven't looked at the code yet.

**Comment by ABuffEr** [comment]
> Just asking, does it add pauses in the middle of numbers? I noticed this behavior but I haven't looked at the code yet.
Simple double spaces, at the moment (I plan to play with SpeechCommands in future dev builds, after the stable version for add-on store).
Thanks for testing!

**Comment by cary-rowen** [comment]
> Simple double spaces, at the moment (I plan to play with SpeechCommands in future dev builds, after the stable version for add-on store).
Can this be an option? I may not need it most of the time, but I don't deny that it is useful.

**Comment by ABuffEr** [comment]
> Can this be an option? I may not need it most of the time, but I don't deny that it is useful.

Well, I think so. As well as I imagine the pause length could be customizable.

**Comment by tareh7z** [comment]
Hi @ABuffEr!
I have tested the latest release of the add-on and so far, I don't see any issues.
What I would like you to consider is adding the following symbols to the add-on, so its functionality can cover these currencies as well:

* ₹
* ₨
* ₽
* ﷼
* ៛
* ₱
* ₣
* ₺
* ₦
* ₪
* ₮
* ₡
* ₵
* ₲
* ₸
* ₭
* ₳
* ₤
* ₾
* ₼

As you can see, there are two symbols for the rupee, which are not the same.
Please don't take this as imposing, but rather as a suggestion. It's entirely up to you whether you choose to implement this or not.

**Comment by tareh7z** [comment]
Hi @ABuffEr!
New old problem:
The issue that still occurs is as follows:
$1.000.000
or
€1.000.000
is read as
1.000 € . 00
or
1.000 $ . 00
The same applies when commas are used between numbers instead of periods.

**Comment by ABuffEr** [comment]
Hi,
new build [here](https://github.com/ABuffEr/numberProcessing/releases/download/v1.0.20240820/numberProcessing-1.0.20240820.nvda-addon)
The reported issue above should fixed, I hope definitely. I optimized currency catching using the Unicode currency block \u20a0-\u20cf, that covers a lot of symbols (including ₿), in addition to the other scattered symbols like $, £, 💶 and so on. And now I do not process speech chunks without numbers, to speedup and avoid undesired effects.
So, this should be a quite stable build, I think.
Thanks for support!

**Comment by tareh7z** [comment]
Hi @ABuffEr!
Thank you for this release.
I will test it for a few days and report the results. At first glance, everything looks good.
