### ISSUE TITLE
Bug with Automatic Number Processing

### ISSUE THREAD

**Issue by tareh7z** [ABuffEr/numberProcessing#9]
For some reason, when I install the add-on version 20240814, number processing is not automatically enabled even if check box for this feature is checked in settings. When I try to enable or disable it using the NVDA+Shift+L shortcut, the add-on always says "Digit processing off". However, when I disable automatic number processing on NVDA startup, toggling between off and on with the NVDA+Shift+L shortcut works.

**Comment by ABuffEr** [comment]
Hi,
sincerely, I'm not able to reproduce this bug.
Can you provide exact steps?
Thanks.

**Comment by tareh7z** [comment]
Hi @ABuffEr!
Sorry if I may have been unclear.
Here are the steps to reproduce this issue:

1. Open the NVDA menu.
2. Go to the "Preferences" submenu, then "Settings".
3. Navigate to the "Number Processing" category.
4. Check the "Processing automatically enabled" checkbox.
5. Press "Apply" and then "OK".
6. Restart NVDA.
7. Press NVDA+Shift+L once. You should hear the message: "Digit processing off".
8. Press NVDA+Shift+L again just once. You will hear the same message.

Repeat all steps from the first to the sixth, including the sixth, but in step 4, instead of checking the "Processing automatically enabled" checkbox, uncheck it.

7. Press NVDA+Shift+L once. You should hear the message: "Digit processing on".
8. Press NVDA+Shift+L again just once. Now you should hear the message: "Digit processing off".

**Comment by ABuffEr** [comment]
Thanks, I have seen. Unfortunately I'm not able to find a simple, maintanable solution to solve the situation at this moment, so I returned to previous behavior in next build.
